version: '2'

services:

  vtiger:
          #build:  7.2.0
    image: javanile/vtiger:latest
    environment:
      - VT_DEBUG=true
      - VT_SITE_URL=https://crm.labs.coronawhy.org/
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 8083:80
      - 20443:443
    volumes:
      - ./:/app
      - ./vtiger:/var/lib/vtiger
    links:
      - mysql
      - adminer
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vtiger.rule=Host(`crm.${traefikhost}`)"
      - "traefik.http.routers.vtiger.entrypoints=web"
      - "traefik.http.services.vtiger.loadbalancer.server.port=80"
      # Uncomment this label if your Traefik instance is using a specific Docker network and replace the network name 
      # This is not necessary if you set your default network in Traefik config/parameters
      # - "traefik.docker.network=your-traefik-network-name"

  adminer:
    image: javanile/adminer
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 20081:8080
    links:
      - mysql

  mysql:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - mysql:/var/lib/mysql:rw
      - ./:/vtiger:rw

  debian:
    image: debian
    working_dir: /app
    command: bash -c "echo 'prevent default'; exit 0"
    volumes:
      - ./:/app:rw

volumes:
  mysql:
